# Generated by Django 2.2.1 on 2019-06-07 11:01

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, verbose_name='Emal')),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='First_name')),
                ('last_name', models.CharField(max_length=30, verbose_name='Last_name')),
                ('email', models.EmailField(max_length=30, verbose_name='Email')),
                ('subject', models.CharField(max_length=30, verbose_name='Subject')),
                ('message', models.TextField(max_length=500, verbose_name='message')),
                ('ip', models.GenericIPAddressField(unpack_ipv4=True)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('none', 'None'), ('books', 'Book'), ('movies', 'Movie'), ('games', 'Game')], default='none', max_length=100, verbose_name='Category')),
                ('image_load', models.ImageField(blank=True, max_length=256, null=True, upload_to='media/blog/images/', verbose_name='')),
                ('title', models.CharField(max_length=100)),
                ('preview', models.TextField(max_length=500)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(max_length=10000)),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
                ('likes', models.IntegerField(default=0, verbose_name='Likes')),
                ('ip', models.TextField(blank=True, default='0.0.0.0-', editable=False, null=True)),
                ('edit', models.TextField(default='edit', editable=False, max_length=50, verbose_name='')),
                ('moderation', models.BooleanField(default=False, verbose_name='Moderation')),
                ('hold', models.BooleanField(default=False, verbose_name='Hold')),
                ('tags', models.ManyToManyField(blank=True, related_name='Tags', to='main.Tags')),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
