# Generated by Django 2.2.1 on 2019-06-09 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190609_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='ip',
        ),
    ]
