# Generated by Django 2.2.1 on 2019-06-09 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_follow_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0', unpack_ipv4=True),
            preserve_default=False,
        ),
    ]
