# Generated by Django 2.2.1 on 2019-06-09 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_follow_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='ip',
        ),
    ]
