# Generated by Django 2.2.1 on 2019-05-28 22:22

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_load', models.ImageField(blank=True, max_length=256, null=True, upload_to='media/reading/images/', verbose_name='')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('html', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
            },
        ),
    ]
