# Generated by Django 2.2.1 on 2019-05-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='hold',
            field=models.BooleanField(default=False, verbose_name='Hold'),
        ),
    ]
