# Generated by Django 2.2.1 on 2019-05-29 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0002_books_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='css',
            field=models.CharField(default='.css-title{font-size: 24px;}', max_length=500),
        ),
    ]
