# Generated by Django 2.2.1 on 2019-05-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read', '0003_books_css'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='css',
            field=models.TextField(default='.css-title{font-size: 24px;}', max_length=1000, verbose_name='CSS'),
        ),
    ]
