# Generated by Django 2.2.1 on 2019-05-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_load', models.ImageField(blank=True, max_length=256, null=True, upload_to='media/instagram/images/', verbose_name='')),
                ('text', models.TextField(blank=True, default='', max_length=3000, null=True)),
                ('tags', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Tags')),
                ('likes', models.IntegerField(blank=True, default=0, verbose_name='Likes')),
                ('views', models.IntegerField(blank=True, default=0, verbose_name='Views')),
                ('date', models.DateField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Post',
                'verbose_name_plural': 'Posts',
            },
        ),
    ]
